define_directive {v:work.edge_detect_top} {.noprune} {1}
define_directive {v:work.edge_detect_top} {.distcompnoprune} {1}
define_directive {v:work.fifo} {.noprune} {1}
define_directive {v:work.fifo} {.distcompnoprune} {1}
define_directive {v:work.sobel} {.noprune} {1}
define_directive {v:work.sobel} {.distcompnoprune} {1}
define_directive {v:work.grayscale} {.noprune} {1}
define_directive {v:work.grayscale} {.distcompnoprune} {1}
define_directive {v:work.edge_detect_top} {.distcompmodetop} {1}
