
`timescale 1 ns / 1 ns

module motion_detect_tb;

    // File Paths
    localparam string BASE_IN_NAME = "src/base.bmp";
    localparam string IMG_IN_NAME  = "src/pedestrians.bmp";
    localparam string IMG_OUT_NAME = "out/output.bmp";
    localparam string IMG_CMP_NAME = "src/img_out.bmp"; // Generated by C code
    
    localparam CLOCK_PERIOD = 10;

    logic clock = 1'b1;
    logic reset = '0;
    
    // Inputs
    logic        base_full;
    logic        base_wr_en = '0;
    logic [23:0] base_din   = '0;
    
    logic        img_full;
    logic        img_wr_en  = '0;
    logic [23:0] img_din    = '0;

    // Output
    logic        out_empty;
    logic        out_rd_en;
    logic [23:0] out_dout;

    // Control & Stats
    logic   base_write_done = '0;
    logic   img_write_done  = '0;
    logic   out_read_done   = '0;
    integer out_errors      = '0;

    localparam BMP_HEADER_SIZE = 54;
    localparam BYTES_PER_PIXEL = 3;

    motion_detect_top #(
        .FIFO_DEPTH(32)
    ) dut (
        .clock(clock),
        .reset(reset),
        .base_full(base_full),
        .base_wr_en(base_wr_en),
        .base_din(base_din),
        .img_full(img_full),
        .img_wr_en(img_wr_en),
        .img_din(img_din),
        .out_empty(out_empty),
        .out_rd_en(out_rd_en),
        .out_dout(out_dout)
    );

    // Clock Generation
    always begin
        clock = 1'b1;
        #(CLOCK_PERIOD/2);
        clock = 1'b0;
        #(CLOCK_PERIOD/2);
    end

    // Reset Generation
    initial begin
        @(posedge clock);
        reset = 1'b1;
        @(posedge clock);
        reset = 1'b0;
    end

    // Main Simulation Process
    initial begin : main_process
        longint unsigned start_time, end_time;

        @(negedge reset);
        wait(base_write_done && img_write_done && out_read_done);
        
        end_time = $time;
        $display("@ %0t: Simulation completed.", end_time);
        $display("Total simulation cycle count: %0d", (end_time-start_time)/CLOCK_PERIOD);
        $display("Total error count: %0d", out_errors);
        $finish;
    end

    // Base Image Reader
    initial begin : base_read
        int i, r;
        int in_file;
        logic [7:0] bmp_header [0:BMP_HEADER_SIZE-1];
        logic [23:0] pixel;
        int width, height, data_size;

        @(negedge reset);
        $display("Loading Base Image: %s", BASE_IN_NAME);
        in_file = $fopen(BASE_IN_NAME, "rb");
        if (!in_file) begin
            $display("Error: Could not open %s", BASE_IN_NAME);
            $stop;
        end

        // Read Header
        r = $fread(bmp_header, in_file, 0, BMP_HEADER_SIZE);
        
        // Skip header
        i = 0;
        while (!$feof(in_file)) begin
            @(negedge clock);
            base_wr_en = 1'b0;
            if (base_full == 1'b0) begin
                // Read 3 bytes
                r = $fread(pixel, in_file); 
                if (r == 3) begin
                     base_din = pixel;
                     base_wr_en = 1'b1;
                end else begin
                     break; // End of file
                end
            end
        end

        @(negedge clock);
        base_wr_en = 1'b0;
        $fclose(in_file);
        base_write_done = 1'b1;
        $display("Base Image Load Done.");
    end

    // Pedestrian Image Reader
    initial begin : img_read
        int i, r;
        int in_file;
        logic [7:0] bmp_header [0:BMP_HEADER_SIZE-1];
        logic [23:0] pixel;

        @(negedge reset);
        $display("Loading Pedestrian Image: %s", IMG_IN_NAME);
        in_file = $fopen(IMG_IN_NAME, "rb");
        if (!in_file) begin
             $display("Error: Could not open %s", IMG_IN_NAME);
             $stop;
        end

        // Read Header
        r = $fread(bmp_header, in_file, 0, BMP_HEADER_SIZE);

        while (!$feof(in_file)) begin
            @(negedge clock);
            img_wr_en = 1'b0;
            if (img_full == 1'b0) begin
                r = $fread(pixel, in_file);
                if (r == 3) begin
                    img_din = pixel;
                    img_wr_en = 1'b1;
                end else begin
                    break;
                end
            end
        end

        @(negedge clock);
        img_wr_en = 1'b0;
        $fclose(in_file);
        img_write_done = 1'b1;
        $display("Pedestrian Image Load Done.");
    end

    // Output Verification & Write
    initial begin : out_write
        int i, r;
        int out_file, cmp_file;
        int h_file;
        logic [23:0] cmp_dout;
        logic [7:0] bmp_header [0:BMP_HEADER_SIZE-1];
        logic [7:0] dump [0:BMP_HEADER_SIZE-1];
        
        @(negedge reset);
        // We need the header from one of the input files to write the output file
        
        h_file = $fopen(IMG_IN_NAME, "rb");
        r = $fread(bmp_header, h_file, 0, BMP_HEADER_SIZE);
        $fclose(h_file);

        out_file = $fopen(IMG_OUT_NAME, "wb");
        cmp_file = $fopen(IMG_CMP_NAME, "rb");
        
        if (!cmp_file) begin
            $display("Warning: %s not found. Run C code first!", IMG_CMP_NAME);
        end

        // Write Header to output
        for (i = 0; i < BMP_HEADER_SIZE; i++) begin
            $fwrite(out_file, "%c", bmp_header[i]);
        end
        // Skip Header in cmp file
        if (cmp_file) begin
            r = $fread(dump, cmp_file, 0, BMP_HEADER_SIZE);
        end

        out_rd_en = 1'b0;
        i = 0; // Pixel count
        
        // Wait for some data
        @(negedge clock);
        
        forever begin
            @(negedge clock);
            out_rd_en = 1'b0;
            
            if (out_empty == 1'b0) begin
                out_rd_en = 1'b1;
                
                // Write to file
                $fwrite(out_file, "%c%c%c", out_dout[23:16], out_dout[15:8], out_dout[7:0]);
                
                if (cmp_file) begin
                    r = $fread(cmp_dout, cmp_file);
                    if (out_dout !== cmp_dout) begin // Use !== to catch X
                         out_errors++;
                         if (out_errors < 10) // Limit spam
                            $display("Error at pixel %0d: Expected %h, Got %h", i, cmp_dout, out_dout);
                    end
                end
                i++;
            end else if (base_write_done && img_write_done) begin
                if (out_empty) begin
                    repeat(100) @(posedge clock);
                    if (out_empty) break; 
                end
            end
        end

        $fclose(out_file);
        if (cmp_file) $fclose(cmp_file);
        out_read_done = 1'b1;
    end

endmodule
