define_directive {v:work.cordic} {syn_black_box} {1}
define_directive {v:work.cordic} {.distcomp_black_box} {1}
define_directive {v:work.cordic} {.noprune} {1}
define_directive {v:work.cordic} {.distcompnoprune} {1}
define_directive {v:work.cordic_top} {.noprune} {1}
define_directive {v:work.cordic_top} {.distcompnoprune} {1}
define_directive {v:work.fifo} {.noprune} {1}
define_directive {v:work.fifo} {.distcompnoprune} {1}
define_directive {v:work.cordic_top} {.distcompmodetop} {1}
