define_directive {v:work.udp_parser_top} {.noprune} {1}
define_directive {v:work.udp_parser_top} {.distcompnoprune} {1}
define_directive {v:work.fifo_ctrl} {.noprune} {1}
define_directive {v:work.fifo_ctrl} {.distcompnoprune} {1}
define_directive {v:work.fifo} {.noprune} {1}
define_directive {v:work.fifo} {.distcompnoprune} {1}
define_directive {v:work.udp_parser} {.noprune} {1}
define_directive {v:work.udp_parser} {.distcompnoprune} {1}
define_directive {v:work.udp_parser_top} {.distcompmodetop} {1}
